// Generated by https://quicktype.io

namespace ECommerceParser.Helpers
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Translation
    {
        [JsonProperty("cache")]
        public Cache[] Cache { get; set; }
    }

    public partial class Cache
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("inputText")]
        public string InputText { get; set; }

        [JsonProperty("sourceLanguage")]
        public string SourceLanguage { get; set; }

        [JsonProperty("outputText")]
        public string OutputText { get; set; }

        [JsonProperty("destinationLanguage")]
        public string DestinationLanguage { get; set; }
    }

    public partial class Translation
    {
        public static Translation FromJson(string json) => JsonConvert.DeserializeObject<Translation>(json, Converter.Settings);
        public static string ToJson(Translation json) => JsonConvert.SerializeObject(json, Formatting.Indented);
    }
}
